dist: trusty
language: python
install:
  - sudo apt-get install -y --force-yes python-virtualenv libleveldb-dev liberasurecode-dev libattr1-dev libleveldb1
  - sudo apt-get install -y --force-yes doxygen
  - virtualenv $HOME/venv && source $HOME/venv/bin/activate
  - pip install --upgrade pip setuptools virtualenv tox
script:
  - python -m json.tool components.json
  - tox -e ci
